---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ceph-csi
spec:
  interval: 1h
  chart:
    spec:
      # renovate: registryUrl=https://ceph.github.io/csi-charts
      chart: ceph-csi-rbd
      version: 3.14.0
      sourceRef:
        kind: HelmRepository
        name: ceph-csi
        namespace: flux-system
      interval: 5m
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  dependsOn:
    - name: cloudflare-tunnel
      namespace: network
  values:
    csiConfig:
      - clusterID: "e4a4c987-4801-40ad-a6ae-bfdecbec3df4" #FSID of ceph cluster
        monitors:
        - 10.0.1.42:6789
        - 10.0.1.46:6789