# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:NTy+f4m4GxdhxqxNaMvrgbE9zsZIa4dW+OmV31cjYLE=,iv:UjiUsh+IUwOiOjQv4p/lI90E7Dm6ThpeDO2nuoQs2MU=,tag:ytujPzMavnWtIpk9u6UQQg==,type:str]
sops:
  age:
    - recipient: age1j2ez3gzftsyr9yr3f8fassc8gfgdcrr3wk80wanreu4xtrlrm5sq423ffa
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4UXJDc3dxd1A3UG5hcVBz
        em5EVVQ3UEplNkx2Nk1VSkVxZW4zci9nZHlRCllhM0pFNkZmbXAyWmRyZ3ZjUFZP
        Nllsa29jbjRqZkxwQVFteit3QkF4TVUKLS0tIHFmVDl4OHVnOHFjYWxmMG1ESzEx
        b1l6a3Q5M3FOcTBrN1BkRzJIS2U2Z0UKaTnEH7nLyShxcPzPM0VarJN+lHzr+0R9
        rg8fHBd+sXTveEcsnX+F+33/viOnmYdt07iwWPsxsNeAfkzD8OhXyw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-07-03T16:02:44Z"
  mac: ENC[AES256_GCM,data:2vdOqGZ0zPXb9GEWouTt/3ZQKdI4aRk1JHTfzRN0MfLsthTre4/xcBJaCtpy+StpgToOX9ommcU5t5s19Do7a5UZJMJYGvz17Fct7tqhwKNjM3EIMwQ/2jQzmkKsNhXuxOEgWx+YukLKv22gQEBRgtUHCLHj6YxSiQ6r5PK4FyY=,iv:5yVUEw+EdCXddUgXHkzxdAfWFVwN3u8T/6wCXkvTPZc=,tag:xguGZm3qsprFo8Pc4W9+Qw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
