# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:NI5/PQY3sfI53efxRHsM+/MGYSsD0Putrq/Ar/HQecair7wwq6X4EQ==,iv:gQAxbVcdJJ2gkjITNTQi9g6/W8WO0Ivc/bg9EUTJNaE=,tag:+dWCidQ4byieBHJsnV+jog==,type:str]
sops:
  age:
    - recipient: age1j2ez3gzftsyr9yr3f8fassc8gfgdcrr3wk80wanreu4xtrlrm5sq423ffa
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHZThDbS9xenhqUlpsdTli
        L285K3BXRmRUdkVwZDR6Q3YwOXAydm9CRDNJCjFMbG5rd2FFWm5XOXNNN3lPaEky
        dVR6cTlWTTIrSkN3Sk13RUt6ZWV3YWMKLS0tIGdONW9LajhzUXBkTnlRakR1bUN3
        cjE5TFphODRHdEViM2ZMR1pneDh0dncK/B+giseCPDMrKph22nXlwYFhjYb20U9B
        6jsmhCxBHG8ysIjWmpcOcGIn6vgHwmBVBxGGibhPA6um5E4S+02r3w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-06-30T19:08:11Z"
  mac: ENC[AES256_GCM,data:uxmXk2aSpLbDNLcG5a5zGtHJNdrIw2FWANPd8s8SyikZFK7tkJDybj85ohUKvlOox3Xh5QYn9jc1wr+66zcA5DFr23atFvZvOQVrA3hNAOOcbxV+eGiGodc7gfUsYiU/0E9WxaeWFIJt9mwCGC+dSq0Zl9jeeIVU2Trja0dP3Iw=,iv:/dAyFXMF0pATQQ/I6mocXf8LtKrjDlqgb/oqlapuj40=,tag:ms3cM7EyDcFFk3YxvijGgQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
