apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:fFUEfG0Wk2qp,iv:4nY/ChTME66xAicFKdI8Tt/52yzkatPfUmWiG6aN8Sk=,tag:90+MS8sMYR4u1ClhD5bbzQ==,type:str]
sops:
  age:
    - recipient: age1j2ez3gzftsyr9yr3f8fassc8gfgdcrr3wk80wanreu4xtrlrm5sq423ffa
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXKy9kbWIyNHEybmdrNWNT
        Nk9sc2FJcGczUDR1OExXQXROY1ZHcnlTV1RvClZsYXBRMGd6NjcyRy92emVCT0xy
        Y2oyRXkveDJuMFVEN2wyQUVQY2xySDAKLS0tIHRRWkdTNG5xMG4yTGN0U1hRNjFH
        a1RtSnNLRTBiRTRLbjUvdDRkbjFybnMKF0aVGKUu1PVXBsXRr5rTGYS6j/ICrvwG
        BhiZAqWIAia9OljJ4Rq1aRJhO7mFud/y9rzPjzLXlazesXZfdE3ztw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-06-30T16:46:49Z"
  mac: ENC[AES256_GCM,data:aI3fGqT/6+C/S4O5BaiMWf43vc1EmpVPeGGb/FDIy0B6QKJ7hT65pzZNdwo5fQs4HfA+slYQy5bpFyHDHeFjvs5VciibJPrNbjC8BVmNxzK79XMhM7bfLHEKffQn25LT4QAIHLra3WRLNKuZDMsEoh7kCpBXFvOspmPn61yR89c=,iv:Wp1XSKV3m0bmhrn1xtQqWx+MazOxUcH3b20V3o1jJXo=,tag:a6iFJXuou3N/gS3sf4Huzg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
